apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kbe3aj5di-python-gitops
  description: This is GitOps manifest for kbe3aj5di-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=kbe3aj5di-python
    backstage.io/kubernetes-id: kbe3aj5di-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kbe3aj5di-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kbe3aj5di-python
