apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kbe3aj5di-python
  janus-idp.io/tekton: kbe3aj5di-python
  backstage.io/kubernetes-id: kbe3aj5di-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kbe3aj5di-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
