apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kbe3aj5di-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kbe3aj5di-python 
  name: kbe3aj5di-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kbe3aj5di-python 
